server.port=spring-cloud-config-server
server.port=8082

spring.datasource.url = jdbc:mysql://localhost:3306/todotasks
spring.datasource.username = dbasys
spring.datasource.password = oracle

spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
spring.datasource.initialization-mode=always


